version-remove

diff --git a/.tekton/task-wes.yaml b/.tekton/task-wes.yaml
--- a/.tekton/task-wes.yaml
+++ b/.tekton/task-wes.yaml
@@ -14,24 +14,6 @@ spec:
     - name: revision
       description: the git revision/commit for the git repo
       default: ""
-    - name: terraform_version
-      description: terraform_version 
-      default: "1.5.7"
-    - name: golang_version
-      description: golang_version 
-      default: "1.21.0"
-    - name: ansible_version
-      description: ansible_version 
-      default: "4.10.0"
-    - name: ansible_core_version
-      description: ansible_core_version 
-      default: "2.11.12"
-    - name: terraform_provisioner_version
-      description: terraform_provisioner_version 
-      default: "2.3.3"
-    - name: python_version
-      description: python_version 
-      default: "3.9"
     - name: git-client-image
       description: The image to use to run git clone commands
       default: alpine/git
@@ -218,18 +200,6 @@ spec:
           value: $(params.repository)
         - name: PIPELINE_DEBUG
           value: $(params.pipeline-debug)
-        - name: terraform_version
-          value: $(params.terraform_version)
-        - name: golang_version
-          value: $(params.golang_version)
-        - name: ansible_version
-          value: $(params.ansible_version)
-        - name: ansible_core_version
-          value: $(params.ansible_core_version)
-        - name: terraform_provisioner_version
-          value: $(params.terraform_provisioner_version)
-        - name: python_version
-          value: $(params.python_version)
       workingDir: "/artifacts"
       imagePullPolicy: Always
       command: ["/bin/bash", "-c"]
@@ -246,6 +216,10 @@ spec:
 
           TF_DIR="/tmp"
 
+          #######################################
+          # IBM Cloud
+          #######################################
+
           echo $'***** Installing IBMCLOUD and Plugins *****\n'
           curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
           ibmcloud plugin install schematics
@@ -258,11 +232,14 @@ spec:
               export GOPRIVATE=github.ibm.com/*
           fi
            
+          #######################################
+          # Golang
+          #######################################
           echo $'***** Installing Golang *****\n'
           yum install wget -y
           [ ! -d "$(pwd)/go" ] && 
-          cd $(pwd) && wget https://go.dev/dl/go${golang_version}.linux-amd64.tar.gz && 
-          tar -C $(pwd)/ -xzf go${golang_version}.linux-amd64.tar.gz && 
+          cd $(pwd) && wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz && 
+          tar -C $(pwd)/ -xzf go1.21.0.linux-amd64.tar.gz && 
           cd $(pwd)/ && 
           echo "export PATH=\$PATH:$(pwd)/go/bin:\$HOME/go/bin" >> ~/.bashrc && 
           echo "export GOROOT=$(pwd)/go" >> ~/.bashrc
@@ -271,35 +248,78 @@ spec:
           which go
           echo $'***** Golang Installed Successfully *****\n'
 
+          #######################################
+          # Make
+          #######################################
+
           echo $'***** Installing Make *****\n'
           yum install make
           make --version 
           echo $'***** Make Installed *****\n'
 
+          #######################################
+          # python
+          #######################################
+
           echo $'***** Installing Python *****\n'
-          yum install python${python_version} -y
-          python${python_version} --version
+          yum install python3.9 -y
+          python3.9 --version
+          
+
+          if python3 --version &> /dev/null; then
+            PYTHON=python3
+          elif python --version &> /dev/null; then
+            PYTHON=python3
+          else
+            echo "python or python3 not detected. Please install python, ensure it is on your \$PATH, and retry."
+            exit 1
+          fi
           echo $'***** Python Installed *****\n'
 
-          echo $'***** Upgrading PIP and Installing Ansible *****\n'
+          #######################################
+          # pip
+          #######################################
+
+          echo $'***** Upgrading/Installing PIP *****\n'
           python3 -m pip install --upgrade pip
           pip install --root-user-action=ignore requests
-          python3 -m pip install ansible==${ansible_version} ansible-core==${ansible_core_version}
+
+          if ! ${PYTHON} -m pip &> /dev/null; then
+            echo "Unable to detect pip after running: ${PYTHON} -m pip. Please ensure pip is installed and try again."
+            exit 1
+          fi
+          echo $'***** Upgraded/Installed PIP *****\n'
+
+          #######################################
+          # ansible
+          #######################################
+
+          echo $'***** Installing Ansible and Ansible core *****\n'
+          python3 -m pip install ansible==4.10.0 ansible-core==2.11.12
           ansible --version
-          echo $'***** PIP Upgraded and Ansible Installed *****\n'
+          echo $'***** Ansible and Ansible core Installed *****\n'
+
+
+          #######################################
+          # terraform-provisioner
+          #######################################
 
           echo $'***** Installing Terraform-Provisioner *****\n'
           curl -sL \
             https://raw.githubusercontent.com/radekg/terraform-provisioner-ansible/master/bin/deploy-release.sh \
             --output /tmp/deploy-release.sh
           chmod +x /tmp/deploy-release.sh
-          /tmp/deploy-release.sh -v ${terraform_provisioner_version}
+          /tmp/deploy-release.sh -v 2.3.3
           rm -rf /tmp/deploy-release.sh
           echo $'***** Terraform-Provisioner Installed *****\n'
 
+          #######################################
+          # terraform
+          #######################################
+
           echo $'***** Installing Terraform *****\n'
-          wget https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip 
-          unzip terraform_${terraform_version}_linux_amd64.zip
+          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip 
+          unzip terraform_1.5.7_linux_amd64.zip
           mv terraform /usr/local/bin/terraform
           terraform --version
           echo $'***** Terraform Installed *****\n'
@@ -309,8 +329,6 @@ spec:
       env:
         - name: PIPELINE_DEBUG
           value: $(params.pipeline-debug)
-        - name: terraform_version
-          value: $(params.terraform_version)
       workingDir: "/artifacts"
       imagePullPolicy: Always
       command: ["/bin/bash", "-c"]
@@ -325,7 +343,7 @@ spec:
             set -x
           fi
 
-          unzip terraform_${terraform_version}_linux_amd64.zip
+          unzip terraform_1.5.7_linux_amd64.zip
           mv terraform /usr/local/bin/terraform
 
           terraform init
@@ -361,8 +379,6 @@ spec:
           value: $(params.key_management)
         - name: PIPELINE_DEBUG
           value: $(params.pipeline-debug)
-        - name: terraform_version
-          value: $(params.terraform_version)
       workingDir: "/artifacts"
       imagePullPolicy: Always
       command: ["/bin/bash", "-c"]
@@ -377,7 +393,7 @@ spec:
             set -x
           fi
 
-          unzip terraform_${terraform_version}_linux_amd64.zip
+          unzip terraform_1.5.7_linux_amd64.zip
           mv terraform /usr/local/bin/terraform
 
           strToArray () {
@@ -431,10 +447,6 @@ spec:
           value: $(params.key_management)
         - name: PIPELINE_DEBUG
           value: $(params.pipeline-debug)
-        - name: terraform_version
-          value: $(params.terraform_version)
-        - name: golang_version
-          value: $(params.golang_version)
       workingDir: "/artifacts"
       imagePullPolicy: Always
       command: ["/bin/bash", "-c"]
@@ -449,7 +461,7 @@ spec:
             set -x
           fi
           
-          unzip terraform_${terraform_version}_linux_amd64.zip
+          unzip terraform_1.5.7_linux_amd64.zip
           mv terraform /usr/local/bin/terraform
 
           cd $(pwd)/ && 
@@ -509,8 +521,6 @@ spec:
           value: $(params.key_management)
         - name: PIPELINE_DEBUG
           value: $(params.pipeline-debug)
-        - name: terraform_version
-          value: $(params.terraform_version)
       workingDir: "/artifacts"
       imagePullPolicy: Always
       command: ["/bin/bash", "-c"]
@@ -525,7 +535,7 @@ spec:
             set -x
           fi
 
-          unzip terraform_${terraform_version}_linux_amd64.zip
+          unzip terraform_1.5.7_linux_amd64.zip
           mv terraform /usr/local/bin/terraform
 
           strToArray () {
